using System;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using SynInvisibleHelmets.Types;
using Noggog;

namespace SynInvisibleHelmets
{
    public class Program
    {
        static Lazy<Setting> LazySettings = new();
        static Setting Config => LazySettings.Value;
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .SetAutogeneratedSettings("Settings", "settings.json", out LazySettings)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "SynInvisHelmets.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            state.LoadOrder.PriorityOrder.Armor().WinningOverrides().ForEach(armor =>
            {
                if (!string.IsNullOrEmpty(armor.Name?.String ?? "") && armor.BodyTemplate != null && armor.BodyTemplate.FirstPersonFlags.HasFlag(BipedObjectFlag.Hair))
                {
                    var na = state.PatchMod.Armors.GetOrAddAsOverride(armor);
                    Console.WriteLine($"Patching {na.Name?.String}");
                    if (na.BodyTemplate != null)
                    {
                        na.BodyTemplate.FirstPersonFlags &= ~BipedObjectFlag.Hair;
                        na.BodyTemplate.FirstPersonFlags |= (BipedObjectFlag)(1 << Config.slotToUse);
                    }
                }
            });
        }
    }
}
